import {test,before,after} from 'node:test';import assert from 'node:assert/strict';import {ObjectId} from 'mongodb';import jwt from 'jsonwebtoken';import {migrateDates} from '../src/migrations/movie-last-updated-migration.js';
process.env.MFLIX_DB_URI='mongodb://127.0.0.1:27018/?replicaSet=offline-rs';process.env.MFLIX_NS='mflix_migration_test_'+process.pid;process.env.SECRET_KEY='isolated-mflix-test-secret';
const {start,offlineUri}=await import('../src/index.js');let runtime,base,db,id,token,email='migration@test.local';
async function call(path,body,method='GET',auth=token){const r=await fetch(base+path,{method,headers:{'content-type':'application/json',...(auth?{authorization:'Bearer '+auth}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()}}
before(async()=>{runtime=await start(0);base='http://127.0.0.1:'+runtime.server.address().port;db=runtime.client.db(process.env.MFLIX_NS);id=new ObjectId();await db.collection('movies').insertMany(Array.from({length:25},(_,i)=>({_id:i===0?id:new ObjectId(),title:'Migration Movie '+i,plot:'Offline astronomy journey',genres:['Drama'],cast:['Test Actor'],countries:['USA'],runtime:100,metacritic:75,tomatoes:{viewer:{numReviews:25-i}}})));await db.collection('movies').createIndex({title:'text',plot:'text'});});
after(async()=>{await db.dropDatabase();await runtime.close()});
test('offline config, pagination, country/text/genre/cast searches and details',async()=>{assert.throws(()=>offlineUri('mongodb+srv://remote.example/db'));let r=await call('/api/v1/movies/');assert.equal(r.data.movies.length,20);assert.equal(r.data.total_results,25);r=await call('/api/v1/movies/search?page=1');assert.equal(r.data.movies.length,5);assert.equal(r.data.total_results,25);assert.equal((await call('/api/v1/movies/search?page=-1')).status,400);for(const q of ['text=astronomy','genre=Drama','cast=Test%20Actor'])assert.equal((await call('/api/v1/movies/search?'+q)).data.total_results,25);assert.equal((await call('/api/v1/movies/countries?countries=USA')).data.titles.length,25);assert.equal((await call('/api/v1/movies/id/'+id)).data.movie._id,id.toString());assert.equal((await call('/api/v1/movies/id/not-an-id')).status,404);assert.equal((await call('/api/v1/movies/config-options')).data.pool_size,50);assert.equal((await call('/api/v1/movies/facet-search?cast=Test%20Actor')).data.movies.length,20);});
test('signup/login/hash/duplicates/preferences and unauthorized admin report',async()=>{assert.equal((await call('/api/v1/user/register',{},'POST')).status,400);let r=await call('/api/v1/user/register',{name:'Migration User',email,password:'password123'},'POST');assert.equal(r.status,200);assert(r.data.auth_token);assert((await db.collection('users').findOne({email})).password.startsWith('$2'));assert.equal((await call('/api/v1/user/register',{name:'Migration User',email,password:'password123'},'POST')).status,400);assert.equal((await call('/api/v1/user/login',{email,password:'wrong'},'POST')).status,401);r=await call('/api/v1/user/login',{email,password:'password123'},'POST');token=r.data.auth_token;assert(token);r=await call('/api/v1/user/update-preferences',{preferences:{favorite:'Drama'}},'PUT');assert.equal(r.data.info.preferences.favorite,'Drama');token=r.data.auth_token;assert.equal((await call('/api/v1/user/comment-report')).status,401);});
test('comment creation/edit/ownership/deletion and admin report',async()=>{assert.equal((await call('/api/v1/movies/comment',{movie_id:id,comment:'offline comment'},'POST','')).status,401);let r=await call('/api/v1/movies/comment',{movie_id:id,comment:'offline comment'},'POST');assert.equal(r.status,200);assert.equal(r.data.comments.length,1);const comment=r.data.comments[0];const foreignResponse=await call('/api/v1/user/register',{email:'other@test.local',name:'Other User',password:'password123'},'POST');const foreign=foreignResponse.data.auth_token;assert.equal((await call('/api/v1/movies/comment',{movie_id:id,comment_id:comment._id,updated_comment:'not owned'},'PUT',foreign)).status,403);assert.equal((await db.collection('comments').findOne({_id:new ObjectId(comment._id)})).text,'offline comment');assert.equal((await call('/api/v1/movies/comment',{movie_id:id,comment_id:comment._id},'DELETE',foreign)).status,403);assert.equal(await db.collection('comments').countDocuments(),1);r=await call('/api/v1/movies/comment',{movie_id:id,comment_id:comment._id,updated_comment:'updated offline'},'PUT');assert.equal(r.data.comments[0].text,'updated offline');await db.collection('users').updateOne({email},{$set:{isAdmin:true}});assert.equal((await call('/api/v1/user/comment-report')).data.report[0].count,1);r=await call('/api/v1/movies/comment',{movie_id:id,comment_id:comment._id},'DELETE');assert.equal(r.data.comments.length,0);});
test('logout removes session and account deletion removes user',async()=>{assert.equal((await call('/api/v1/user/logout',{},'POST')).data.success,true);assert.equal(await db.collection('sessions').countDocuments({user_id:email}),0);assert.equal((await call('/api/v1/user/session')).status,401);token=(await call('/api/v1/user/login',{email,password:'password123'},'POST')).data.auth_token;assert.equal((await call('/api/v1/user/delete',{password:'password123'},'DELETE')).data.success,true);assert.equal(await db.collection('users').countDocuments({email}),0)});

test('date migration converts valid dates, preserves invalid strings, and repeats safely',async()=>{await db.collection('movies').updateOne({_id:id},{$set:{lastupdated:'2020-01-02T00:00:00Z'}});await db.collection('movies').updateOne({title:'Migration Movie 1'},{$set:{lastupdated:'unknown'}});assert.equal(await migrateDates(db),1);assert((await db.collection('movies').findOne({_id:id})).lastupdated instanceof Date);assert.equal(await migrateDates(db),0)});
