import {Component,HostListener,OnDestroy,ChangeDetectionStrategy} from '@angular/core';import {DomSanitizer} from '@angular/platform-browser';import {CommonModule} from '@angular/common';import {FormsModule} from '@angular/forms';import {courseCodes} from './course-codes';import {validators} from './validators.js';
@Component({changeDetection:ChangeDetectionStrategy.Eager,selector:'app-root',standalone:true,imports:[CommonModule,FormsModule],templateUrl:'./mflix.html'})
export class Mflix implements OnDestroy{
 route=location.pathname;movies:any[]=[];movie:any=null;total=0;page=0;mode='text';query='';country='USA';countries:any[]=[];facets:any=null;user:any=null;admin=false;error='';busy=false;name='';email='';password='';comment='';editing='';updated='';preferences:any={preferred_language:'',favorite_cast:''};report:any[]=[];tickets=Object.keys(validators);results:any={};readyName='';copied='';ready:Promise<any>;
 video=false;online=navigator.onLine;rain:any;rainDelay:any;videoUrl:any;
 constructor(private sanitizer:DomSanitizer){try{const old=JSON.parse(localStorage.getItem('state')||'null');if(old?.auth_token)this.user=old}catch{}this.ready=this.initialize()}
 async initialize(){if(this.user){try{this.user={...this.user,info:(await this.api('user/session')).info};this.store()}catch{this.user=null;this.store()}}await this.load()}
 @HostListener('window:popstate')back(){this.stopRain();this.route=location.pathname;void this.load()}
 go(route:string,event?:Event){event?.preventDefault();this.stopRain();history.pushState({},'',route);this.route=route;void this.load()}
 async api(path:string,body?:any,method='GET'){const res=await fetch('/api/v1/'+path,{method,headers:{'content-type':'application/json',...(this.user?.auth_token?{Authorization:'Bearer '+this.user.auth_token}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});const data=await res.json();if(!res.ok)throw new Error(typeof data.error==='string'?data.error:Object.values(data).join('; '));return data}
 async attempt(action:()=>Promise<any>){this.error='';this.busy=true;try{return await action()}catch(e){this.error=(e as Error).message;return null}finally{this.busy=false}}
 async load(){return this.attempt(async()=>{if(this.route.startsWith('/movies/id/')){this.movie=(await this.api('movies/id/'+this.route.split('/').pop())).movie;this.startRain()}else if(this.route==='/'){await this.search(this.page)}else if(this.route==='/country-results'){await this.byCountry()}else if(this.route==='/account'){if(!this.user){this.go('/login');return}this.preferences={preferred_language:'',favorite_cast:'',...this.user.info?.preferences}}else if(['/admin','/user-report'].includes(this.route)){if(!this.user){this.go('/login');return}await this.api('user/admin');this.admin=true;if(this.route==='/user-report')this.report=(await this.api('user/comment-report')).report}})}
 async search(page=0){const q=encodeURIComponent(this.query);const data=await this.api(this.mode==='facet'?'movies/facet-search?cast='+q+'&page='+page:'movies/search?'+this.mode+'='+q+'&page='+page);this.page=page;this.movies=data.movies;this.total=data.total_results;this.facets=data.facets||null}
 poster(m:any){return m.poster&&(this.online||m.poster.startsWith('/')||m.poster.startsWith('data:'))?m.poster:'/assets/poster.svg'}
 posterError(event:Event){const img=event.target as HTMLImageElement;if(!img.src.endsWith('/assets/poster.svg'))img.src='/assets/poster.svg'}
 related(mode:string,value:string){this.mode=mode;this.query=value;this.page=0;this.go('/')}
 watch(){this.video=true;this.videoUrl=this.sanitizer.bypassSecurityTrustResourceUrl('https://www.youtube.com/embed/'+(Math.random()<0.5?'6gGXnE1Dbh0':'dQw4w9WgXcQ')+'?autoplay=1')}
 stopRain(){clearInterval(this.rain);clearTimeout(this.rainDelay)}ngOnDestroy(){this.stopRain()}
 startRain(){this.stopRain();if(!['573a13a2f29313caabd0b8f3','573a139bf29313caabcf3d23','573a13a3f29313caabd0d923','573a13a7f29313caabd1a006'].includes(this.movie?._id))return;this.rainDelay=setTimeout(()=>{const c=document.querySelector<HTMLCanvasElement>('#matrix-poster'),ctx=c?.getContext('2d');if(!c||!ctx)return;const chars=Array.from('田由甲申甴电甶男甸甹町画甼甽甾甿畀畁畂畃畄畅畆畇畈畉畊畋界畍畎畏畐畑'),drops=Array(30).fill(1);this.rain=setInterval(()=>{ctx.fillStyle='rgba(0,0,0,0.05)';ctx.fillRect(0,0,300,444);ctx.fillStyle='#0f0';ctx.font='10px sans-serif';drops.forEach((y,i)=>{ctx.fillText(chars[Math.floor(Math.random()*chars.length)],i*10,y*10);drops[i]=y*10>444&&Math.random()>.975?0:y+1})},33)},1500)}
 async nextPage(){await this.attempt(()=>this.search(this.page+1))} async previousPage(){await this.attempt(()=>this.search(this.page-1))} async attemptCountry(){await this.attempt(()=>this.byCountry())}
 async runSearch(){await this.attempt(()=>this.search(0))}
 async byCountry(){this.countries=(await this.api('movies/countries?countries='+encodeURIComponent(this.country))).titles}
 async auth(){await this.attempt(async()=>{const data=await this.api('user/'+(this.route==='/signup'?'register':'login'),{name:this.name,email:this.email,password:this.password},'POST');this.user=data;this.password='';this.store();this.go('/')})}
 store(){try{if(this.user)localStorage.setItem('state',JSON.stringify(this.user));else localStorage.removeItem('state')}catch{this.error='Could not save login in this browser.'}}
 async logout(){await this.attempt(async()=>{await this.api('user/logout',{},'POST');this.user=null;this.admin=false;this.store();this.go('/')})}
 async savePrefs(){await this.attempt(async()=>{this.user=await this.api('user/update-preferences',{preferences:this.preferences},'PUT');this.store();this.go('/')})}
 async postComment(){await this.attempt(async()=>{const data=await this.api('movies/comment',{movie_id:this.movie._id,comment:this.comment},'POST');this.movie.comments=data.comments;this.comment=''})}
 async editComment(id:string){await this.attempt(async()=>{const data=await this.api('movies/comment',{movie_id:this.movie._id,comment_id:id,updated_comment:this.updated},'PUT');this.movie.comments=data.comments;this.editing=''})}
 async deleteComment(id:string){if(!confirm('Delete this comment?'))return;await this.attempt(async()=>{this.movie.comments=(await this.api('movies/comment',{movie_id:this.movie._id,comment_id:id},'DELETE')).comments})}
 async validate(ticket:string){this.results[ticket]={state:'Running'};try{await (validators as any)[ticket]()((action:any)=>{if(action.type?.includes('SUCCESS'))this.results[ticket]={state:'Passed',code:courseCodes[ticket]};else if(action.type?.includes('ERROR'))this.results[ticket]={state:'Failed',message:action.error?.message||'Original course assertion failed; check the required sample dataset.'}});if(this.results[ticket].state==='Running')this.results[ticket]={state:'Failed',message:'Validator did not return a result.'}}catch(e){this.results[ticket]={state:'Failed',message:(e as Error).message}}}
 async copy(ticket:string){await navigator.clipboard.writeText(this.results[ticket]?.code||'');this.copied=ticket}
}
